name: custom-log-regression
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
  - pip
  - flake8
  - pandas
  - pytest
  - scikit-learn
  - category_encoders=2.0.0
  - pydocstyle
  - flake8
